src/util/pointProjector.js
This is a quick fix for the point projection to/from patient space.
=> Fix for reference line point projection

src/stackTools/stackPrefetch.js
Quick fix for a bug in stackPrefetch
=> Bugfix for stack prefetch

examples/allImageTools/index.html, examples/alltouchtools/index.html, examples/mobileTouch/index.html
Addresses issue #18
Though personally I would prefer if we linked to a relative copy of the bootstrap CSS file, so that local debugging isn't done on an ugly version of the examples.
=> Fix Mixed Content warning

src/imageTools/AngleTool.js, src/imageTools/ellipticalRoi.js, src/imageTools/lengthTool.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js
marked drawn shapes as active, to be able to identify &
delete/manipulate them from outside the library.
Now I can do:
``` javascript
$(document).on('keyup', function (evt) {
//might need to filter based on target
if (evt.keyCode == 46) { //delete
var removed = false;
_.each(['length', 'ellipticalRoi', 'rectangleRoi', 'angle', 'probe'], function (shape) {
var data = (cornerstoneTools.getToolState(rawElement, shape) || {}).data || [];
for (var idx = data.length - 1; idx >= 0; idx--) {
if (data[idx].active) {
data.splice(idx, 1);
removed = true;
}
}
});
if(removed)
cornerstone.updateImage(rawElement);
}
});
```
=> marke highlighted shapes as active. Possibility to delete/manipulate selection

src/stackTools/progressIndicator.js
1. Draw bar at bottom of image showing scroll position of stack, as well as which images in the stack have loaded. (`scrollIndicator`)
2. While image is loading into element, show percent loaded (`loadingIndicator`)
=> Add progress/scroll indicator tool

examples/annotation/index.html
Fixes the issue of being unbale to change labels with firefox.
=> Separate dialog polyfill for entering and changing labels.

src/imageTools/rectangleRoi.js
Also, drawHandlesOnHover config is added into rectangleRoi tool.
=> Fix issues with rectangleRoi tool

src/stackTools/playClip.js
Cornerstone playClip tool now supports playing variable frame rate instances while maintaining full backwards compatibility with existing API.
=> Cornerstone playClip tool now supports playing variable frame rate instances.

examples/exampleNumberMetaDataProvider.js, examples/exampleTextImageLoader.js, examples/stackImagePositionOffsetSynchronizer/index.html
Use a custom image loader that loads images with numbers and different z-values for position.
=> Improve example for Offset Position Synchronizer

examples/alltouchtools/index.html, examples/seedPoints/index.html
=> Fix addEventListener bug in examples

src/imageTools/rotate.js, src/imageTools/simpleTouchTool.js
Fixes #359 
See #359
See #359 
No
I had to introduce a `simpleTouchTool` function as `touchDragTool` does too many assumptions (as the `dragCallback` must have the initial rotation and mouse location added by using `bind`).
=> Improved default strategy of rotate. Fixes #359

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/length.js, src/imageTools/simpleAngle.js, src/util/lineSegDistance.js
This utility function simplifies the logic involved in the `pointNearTool` function for a number of image tools.
=> Add a lineSegDistance function

src/imageTools/freehand.js, src/imageTools/magnify.js, src/imageTools/wwwcRegion.js, src/imageTools/zoom.js, src/manipulators/moveAllHandles.js, src/manipulators/moveHandle.js, src/manipulators/moveNewHandle.js, src/manipulators/moveNewHandleTouch.js, src/synchronization/stackImageIndexSynchronizer.js, src/synchronization/stackScrollSynchronizer.js, src/timeSeriesTools/incrementTimePoint.js, src/util/clip.js, src/util/scroll.js
Adds `clip` and `clipToBox` utility functions to simplify the common operations of restricting scalars and 2d points to a fixed range.
=> Add clip and clipToBox functions

src/imageTools/rotate.js
=> Calculate correct center point for rotation. Fixes #416

src/synchronization/stackImagePositionOffsetSynchronizer.js
* **What kind of change does this PR introduce?** fixes https://github.com/cornerstonejs/cornerstoneTools/issues/419
* **Does this PR introduce a breaking change?** no
=> Added checks to ensure ImagePlane is set (fixes #419)

src/util/scroll.js
=> Use exported EVENTS constants for missing event names in string (#369)

src/imageTools/magnify.js
Fixes a bug which was introduced when the event callback args were changed.
issue #412 
No more exceptions.
No.
I would love to write tests for this. However, I'm not seeing a lot of examples around how the events system is tested, or examples of tests for this or other tools. I spent 10 minutes or so trying to get something rolling but was unsuccessful.
fixes …
=> fix magnify tool callbacks to conform to new args 

src/imageTools/freehand.js
Simply refactors the pointNearTool function in the freehand tool so that it takes the same parameter arguments as other tools, for use with the eraser tool and for longer term compatibility.
=> Freehand pointNearTool refactor

.circleci/config.yml, package.json
This is hard to test without merging, so there may be multiple merges while I try to get this right
=> CircleCI config and package.json

src/stackTools/scrollIndicator.js
=> Fix typo: heigh -> height

src/stackTools/scrollIndicator.js
Follow up on #455, there was more than one bug :-( I hope I have them all fixed now.
Apologies once again!
=> Fix scroll indicator

examples/00-test/index.html, src/fancy-tools/rotateTool.js, src/fancy-tools/rotateTool.test.js, src/fancy-tools/shared/angleBetweenPoints.js, src/index.js
TODO: Figured out a better way to handle mouseDown as I need to store the initialRotation and I am not able to store it only with mouseDrag callback.
=> WIP: RotateTool v3

src/fancy-tools/freehandMouseTool.js
Just a small update of the freehandMouseTool to fit in with the #521 API update.
=> Updated freehandMouseTool handle deletion/creation to PR #521 API.

src/imageTools/freehand.js
Fixing the build that was KO'd by a previous freehand fix.
=> Freehand - fixed missing element declaration

examples/annotation/index.html
- Click events was not being removed correctly. 
- Fix: Make sure to remove all events on dialog before close it. 
(Closes issue #554)
=> Fix arrowAnnotate example

docs/latest/SUMMARY.md, docs/latest/plugins/index.md, docs/latest/plugins/modules.md, src/store/modules/brushModule.js
Started plugin documentation: how to create and register modules.
=> 3rd part module creation and registration docs.

src/eventDispatchers/mouseEventHandlers/mouseDown.js, src/eventDispatchers/mouseEventHandlers/mouseDownActivate.js, src/eventDispatchers/mouseEventHandlers/mouseDrag.js, src/eventDispatchers/mouseEventHandlers/mouseMove.js
Fixes an issue whereby active touch tools could steal events intended for mouse input.
=> Fixed touch tools consuming mouse events.

src/stateManagement/toolState.js, src/tools/FreehandMouseTool.js, src/util/freehand/FreehandLineFinder.js, src/util/freehand/insertOrDelete.js
Fixes the insert/delete handle functionality, that must have broken around the time we changed class capitalization.
=> vNext freehand insert fix

docs/latest/third-party-functionality/imports.md, docs/latest/third-party-functionality/tools.md, examples/brush/index.html, examples/crosshairs/index.html, examples/freehand/index.html, examples/thirdParty/index.html, index.html, src/index.js, src/init.js, src/lib.js
The instance made integration in applications a little clunky at this stage. Fully encapsulated instanced could be useful in the future, but the half-half scenario we've had in vNext has been axed.
=> Removed the idea of a 'cornerstoneTools' instance for v3.

src/index.js
Fixing requestPoolManager top level export.
=> correclty exposed requestPoolManager.

examples/stack/index.html, examples/textImageLoader.js, src/index.js
An example to ease interaction with large image stacks. For example testing bahaviour of different types of input devices as mouse wheels and touchpads.
Current examples only contain three images in the stack.
see https://github.com/cornerstonejs/cornerstoneTools/issues/643
This example lets the user select the size for a test stack and generates synthetic images with frame numbers.
No …
=> Stack example

src/index.js
=> expose toolStyle.

src/lib.js
=> Fix broken build.

src/lib.js
Need this for a 3rd party tool ;)
=> Fix: Export `drawing/textBoxWidth`

src/tools/MagnifyTool.js
We switched the callbacks to `enabledCallback` and `disabledCallback`
=> fix callback hooks

src/eventDispatchers/mouseEventHandlers/mouseMove.js
Fixed canvas cursors not rendering when multiple tools are active, and only some have cursors.
=> vNext - Multiple active tools canvas cursor fix.

.babelrc, config/webpack/webpack-base.js, package-lock.json, package.json, src/eventListeners/onImageRenderedBrushEventHandler.js
Attempt to fix `async`/`await` issues
=> Add IE 11 as a target

src/tools/BidirectionalTool.js
Bug fix for the Bidirectional tool on vNext. Previously, the configuration setup was not working properly.
Setting configuration on the bidirectional tool breaks the tool.
It no longer breaks the tool. Configuration changes have effects as expected.
No
=> vNext: fix(bidirectional-tool): Fix configuration for Bidirectional tool

src/tools/BidirectionalTool.js
Distance threshold is too large, so it's very challenging to select the perpendicular line
Distance threshold has been shrunk, so it's easier to select the perpendicular line
No
=>  fix(bidirectional-tool): Shrink overly large distance threshold

docs/latest/third-party-functionality/item-types.md
Updates module docs to include `removeEnabledElementCallback`.
=> vNext - Updated docs to include removeEnabledElementCallback.

src/stackTools/stackPrefetch.js
- Removing unused EVENTS
- Using cornerstone-core event name.
=> fix(stackPrefetch)

src/tools/annotation/bidirectionalTool/invertHandles.js, src/tools/annotation/bidirectionalTool/preMouseDownCallback.js
- Bidirectional tool: Add invertHandles to keep behaviour consistent if long/short axis swap roles
- Bidirectional tool: Hide cursor while interacting with handles, switch to 'move' cursor CSS value while interacting with attached textbox
- Long axis / short axis behaviour does not switch if short axis becomes longer than long axis
- Whichever axis is longer acts as the pivoting axis
- …
=> Bidirectional fixes 6

package-lock.json, src/tools/base/BaseBrushTool.js, src/tools/brush/BrushTool.js
This PR splits the `BrushTool` into two strategies:
- Overlapping: Segmentations on an image may overlap. This is the default mode.
- Non-overlapping: Segmentations on an image cannot overlap. Drawing with one color erases other segmentations in the same region.
=> Overlapping and non-overlapping brush strategies.

src/stackTools/fusionRenderer.js
I added stackTools/fusionRenderer.render to return a Promise.
That function return undefined.
That function return a Promise.
If you call promise.then(...), then ... is called after done rendering.
=> add promise to fusionRenderer.render

index.html, package-lock.json, src/tools/base/BaseBrushTool.js
Invalidates all the brush data for an enabledElement and re-renders the element.
=> vNext - add invalidateBrushOnEnabledElement static method to BaseBrushTool

src/tools/annotation/EllipticalRoiTool.js, src/tools/annotation/RectangleRoiTool.js, src/util/ellipse/calculateEllipseStatistics.js
Tiny fix where our `bool` was always `true`
=> Fix showHounsfieldUnits bool settings

src/util/freehand/FreehandLineFinder.js, src/util/freehand/insertOrDelete.js
Fix for point insertion when the freehand tool is changed name.
=> [vNext] Fix for point insertion on freehand.

.eslintrc.js, src/util/ellipse/calculateEllipseStatistics.test.js
=> Update .eslintrc.js so that npm run lint behaves as expected

.eslintrc.js, examples/freehandRoi/index.html, src/imageTools/freehand.js
Updated the freehand example to demonstrate the functionality/fix
Fix deactivating/canceling freehand while drawing is not working #784 
Error in the debugger
Fix the error in the debugger and delete the freehand if not enough handles to close.
No
To make merging easier, this branch is forked from the "freehand-fireModifiedEvent-774" branch and is to be merged …
=> Fix deactivating/canceling freehand while drawing is not working #784

examples/toolState/index.html, src/util/freehand/dragObject.js
Updated the toolstate example to show the load/save of freehand
Fix Freehand handles not closed after loading state data #775
As described here: Issue #775 
Fixed.
No
=> Fix Freehand handles not closed after loading state data. Issue #775

src/tools/OverlayTool.js
=> fix overlay tool

src/tools/annotation/FreehandMouseTool.js, src/util/freehand/FreehandLineFinder.js, src/util/freehand/insertOrDelete.js
Update the freehand tool after add/remove point functionality broke after recent changes to the freehand toolData schema.
=> Fix insertOrDelete for freehand tool after recent changes to toolData schema.

package-lock.json, src/tools/annotation/FreehandMouseTool.js
Previously new points wouldn't be added to the `FreehandMouseTool` if the mouse was close to the origin node. Now you may draw as close as you like (respecting `spacing` configuration). Mousing up within the `completeHandleRadius` will still complete the contour.
=> fix(Freehand Tool): UX improvements to closing contours.

package.json
=> chore(package.json): Changed main and module to point to unminified

README.md
> This library attempts to solve these problems, and in a highly pluggable and extensible way. 
=>
> This library solves these problems in a highly pluggable and extensible way.
=> Increased the levels of optimisim in the README.

docs/latest/book.json, docs/latest/custom-tools/adding-mixins.md, docs/latest/custom-tools/creating-your-tool.md, docs/latest/custom-tools/event-dispatcher-callbacks.md, docs/latest/custom-tools/index.md, docs/latest/custom-tools/mode-change-callbacks.md
Documentation update. This is related to a recent issue: #878 
The "Custom Tools" docs make sense for someone creating a tool to be included within the cornerstoneTools repo.
This mostly comes down to the docs using:
```js
import BaseTool from './../base/BaseTool.js';
```
Update the code examples to use:
```js
import csTools from 'cornerstone-tools';
const BaseTool = csTools.import('base/BaseTool');
```
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application …
=> Update to custom tools documentation

docs/latest/index.md
docs
bad link
fixed link...
no
(might want link to guidelines in template -- I'm going to assume this is innocuous enough for it to not possibly not match guidelines)
=> Fix doc link to globalConfigurationModule.js

src/tools/cursors/MouseCursor.js
Throughout the WIP it seems I forgot to publish, added an appropriate commit for the CI.
=> SVG Cursor publish PR

package.json
=> vNext bumped version number.

docs/latest/anatomy-of-a-tool/configuration.md, docs/latest/anatomy-of-a-tool/modes.md
=> updating documentation to fix mode commands name

src/tools/base/BaseBrushTool.js
Align the brush completed event data with the other tools
1. toolType instead of toolName
2. The brush toolState is sent for all segmentation.
1. Used toolName to follow the new v3 naming convention
2. selected the brush data for the current segmentation.
Maybe
=> update brush completed event with expected data fields

docs/latest/README.md, docs/latest/index.md
Feature that includes Netlify badge
Does not have any badge to examples page
Presented the badge in docs file that links to examples page
No, it doesn't
=> docs(netlify): Add Netlify badge to top of docs page

src/eventListeners/onImageRenderedBrushEventHandler.js
=> feat: image id specific per segmentation brush opacity/alpha

.babelrc, package.json
Issue [here](https://github.com/OHIF/Viewers/issues/515)
[here](https://github.com/OHIF/Viewers/issues/515)
Included configuration to support old browser version's code.
No, it doesn't break any part of the code.
=> Includes configuration for IE11 and to support used browsers

examples/README.md
A update for the examples README for using docker in the development process instead of installing ruby & gem locally
You have to have ruby/gem/jerkyll installed on your machiene
I added a simple command to run the jerkyll watch/serve in dicker
No
=> update example README with Docker development workflow

src/eventDispatchers/touchEventHandlers/tap.js, src/manipulators/moveAllHandles.js, src/manipulators/moveHandle.js, src/manipulators/moveNewHandle.js, src/tools/annotation/AngleTool.js, src/tools/annotation/ArrowAnnotateTool.js, src/tools/annotation/bidirectionalTool/addNewMeasurement.js, src/tools/annotation/bidirectionalTool/handleSelectedMouseCallback.js, src/tools/annotation/bidirectionalTool/handleSelectedTouchCallback.js, src/util/findAndMoveHelpers.js
=> makes doneMoveCallback explicitly Tool API and not user API

index.html, netlify-example/brush/index.html, netlify-example/crosshairs/index.html, netlify-example/metaDataProvider.js, src/index.js, src/store/modules/brushModule.js, src/tools/segmentation/SphericalBrushTool.js, src/tools/segmentation/index.js
A spherical brush implementation for `cornerstoneTools`.
The brush paints outwards from the input slice in both directions on slices that have `imagePlane` metadata accessible from a `cornerstone` metadata provider. The brush stops looking for more slices in that direction when either no `imagePlane` metadata is found, or when a slice is out of the influence range of the brush.
=> vNext - spherical brush

src/util/segmentation/operations/correction.js, src/util/segmentation/operations/floodFill.js, src/util/segmentation/operations/getPixelPathBetweenPixels.js, src/util/segmentation/operations/getPixelPathBetweenPixels.test.js
Correction Tool for `vNext` using a slightly modified Tobias Heimann Correction Algorithm in order to try to do it quick in the browser on the CPU.
Using the stroke given, determine which action(s) to perfom:
- Stroke starts and ends inside a segmentation: Behaves as an subtractive freehand scissors.
- Stroke starts and ends outside a segmentation: Behaves as an additive freehand scissors.
- Stroke out-in-out: Section is subtracted.
- Stroke in-out-in: Section is added.
It could further be improved by multithreading operation chains with workers.
=> vNext-CorrectionTool

src/store/modules/brushModule.js, src/util/pointInImage.js, src/util/segmentation/operations/correction.js
Just adds a simple helper to the brush store to get the current segment and metadata if its there.
=> Add helper to get the segment at the mouse position.

index.html, netlify-example/brush/index.html, package.json, src/version.js
Fix the merge tags left in the 4.0 release demo.
=> fix(index.html): Fixed the merge of the index.html demo.

src/index.js, src/store/isToolActiveForElement.js, src/tools/base/BaseBrushTool.js
Renamed isToolActive to isToolActiveForElement and expose it as top
level API.
=> feat: 🎸 Expose isToolActiveForElement

src/util/clip.js
* add part of export for clip.js, because `lib.js` import function `clip` by part import
=> fix(src/util/clip.js): fix lib.js import part of clip error

docs/v3/custom-tools/mode-change-callbacks.md, src/util/clip.js
=> docs: fix docs error

src/init.js, src/mixins/segmentation/renderBrushMixin.js, src/store/modules/globalConfigurationModule.js
Related: https://github.com/cornerstonejs/cornerstoneTools/issues/1084
=> fix: flag to disable auto resize

netlify-example/brush/index.html
Add correct semantic release commit.
=> Volume statistics calculations (cutsemantic release)

src/tools/annotation/ArrowAnnotateTool.js
Feature.
Currently we cannot access event details inside getTextCallback of arrow annotation tool.
Now we can access event details inside getTextCallback of arrow annotation tool.
No breaking change.
=> Add event details to arrow tool getText callback

docs/latest/modules/segmentation.md
Add docs and trigger CI build.
=> feat: 🎸 Optional Float32Array storage for segmentations (#1167)

src/stateManagement/imageIdSpecificStateManager.js
=> fix: clearElementToolState

src/tools/annotation/bidirectionalTool/addNewMeasurement.js
=> fix: 🐛 Error moving other tools' handles with bidirectional

src/store/modules/segmentationModule/setLabelmap3D.js
=> fix: 🐛 Seg load colormap fix

src/eventDispatchers/mouseEventHandlers/addNewMeasurement.js, src/manipulators/moveNewHandle.js
=> Fix: Avoid completed event when outside image

src/tools/annotation/ArrowAnnotateTool.js
Arrow "completing" before text entry caused a lot of workflow issues if you wanted to key off the completed event, so it now happens _after_ the annotation label has been entered.
Also you can now give the ArrowAnnotate tool blank labels by setting the new `allowEmptyLabel` configuration option to `true` (default false).
=> feat: 🎸 Make arrow only complete on text entry, and allow blank

src/drawing/drawTextBox.js
Just remove an extra comment line
=> Removing duplicated comment line from drawTextBox.js

src/tools/annotation/RectangleRoiTool.js
=> fix: push stdDev to separate line for non-SUV modalities

docs/latest/book.json, docs/previous/v2/book.json, docs/previous/v3/book.json
=> docs: Remove sitemap plugin because it is breaking gitbook deploys

src/lib.js
This PR is a feature to expose the function getActiveTools.
https://github.com/cornerstonejs/cornerstoneTools/issues/1214
Now we wil be able to have access to getActiveTool function via :
cornerstoneTools.importInternals('util/getActiveTool');
No.
=> Expose getActiveTool from Utils

src/eventListeners/touchEventListeners.js
Bug fix,
[memory leak](https://github.com/cornerstonejs/cornerstoneTools/issues/1330#issue-754067547)
fix memory leak
no
=> fix: fix memory leak

src/stackTools/stackPrefetch.js
=> fix: Add reverse() back when adding images to queue in stackPrefetch

src/tools/annotation/BidirectionalTool.test.js, src/tools/annotation/bidirectionalTool/renderToolData.js
- [ x] The commit message follows our guidelines
=> fix bidirectional color customization
