src/imageTools/zoom.js
This is a small fix for the click / drag to zoom functions. The tool normally changes viewport scale and then translates the image to zoom in on the clicked location. When rotations or flips were applied to the image, however, this translation would go wrong and the image would be translated off screen.
All I've done is borrow some of the code from pageToPixel and used it to correct the translation in these cases.
The easiest way to test this is to include cornerstoneTools and add:
```javascript
cornerstoneTools.mouseInput.enable(element);
cornerstoneTools.zoom.activate(element, 1);
```
to the cornerstone example here:
https://github.com/chafey/cornerstone/blob/master/example/flip%26rotation/index.html
=> BF: Zoom tool now works properly after rotation / flipping

examples/stackScroll/index.html
Here's a small PR to demonstrate how to link HTML5 Range input (sliders) to the stack position. For now I just included it in the stackScroll example. If you think I should split it into a separate example, just let me know.
=> Added HTML5 Range input to stackScroll example

examples/allImageTools/index.html
This is just a bit of cleanup for the allImageTools example. It also fixes issue #19 by changing onViewportUpdated to use CornerstoneImageRendered. I'm not sure if this is appropriate, but it works and I don't see the CornerstoneViewportUpdated event in the cornerstone code anywhere
.
=> Cleanup of allImageTools example

examples/index.html, examples/stackProgress/index.html
This came up on the google group (https://groups.google.com/forum/#!topic/cornerstone-platform/VxuF921Q42I) so I thought I'd share my implementation.
You just monitor CornerstoneImageLoaded and use an object to slice imageIds out of an array when they've been loaded.
=> Example for monitoring image loading progress in a stack

src/stackTools/stackPrefetch.js
This is a very tiny fix for a bug that occurs when you use something like this (some stuff left out, obviously):
```` javascript
var stack = {
currentImageIdIndex : currentImageIdIndex,
imageIds: imageIds
};
cornerstone.loadAndCacheImage(imageIds[currentImageIdIndex])
cornerstoneTools.stackPrefetch.enable(element);
````
using any value of  ````currentImageIdIndex ```` other than 0, the prefetching would not grab the entire stack. This is because the stackPrefetch code assumed that you had already loaded ````imageIds[0]````.
Switching the initial value of ````prefetchImageIdIndex```` to -1 now forces ````imageIds[0]```` to be loaded.
=> Bug fix for stack prefetch ignoring 0th image

examples/stackScroll/index.html
Small fixes in the stackScroll example. Some weirdness was causing the FPS trigger to fail, and I also forgot to parse the range slider value to an integer.
You can test it here:
https://rawgit.com/swederik/cornerstoneTools/b4f2eaecca1dbba03bf42b4a0d055d015400d67a/examples/stackScroll/index.html
=> Fixed FPS and range value for StackScroll example

src/stackTools/stackPrefetch.js
The fact that the errors were occuring for the currentTarget made me suspect I was somehow enabling the wrong element in my application, but I've done a lot of testing and I'm 99% sure this is not actually
happening.
For more information, please see this post: https://groups.google.com/forum/#!msg/cornerstone-platform/uU09JPyWJTU/1NhQXaMeBQAJ
=> Fix 'element not enabled' errors.

src/imageTools/magnify.js
Otherwise strange behaviour occurs when the user just clicks on the image while the tool is active. For example, the cursor will stay hidden.
=> Turn off on click events

src/inputSources/touchInput.js
The "panmove"-Event only fires when using a single finger.
More fingers may be added while panning.
But if the panning ist started with multiple fingers, the "panmove" event doesen't fire.
Added "rotate.recognizeWith(pan);" to fix this.
Now the "panmove" event is fired when starting with multiple fingers.
=> fixed multitouch panning

src/stackTools/stackPrefetch.js
`clearTimeout` (`onImageUpdated`) is not doing anything because `setTimeout` is being called instantaneously. This results in too many `prefetch` calls when viewing a multi-frame instance in OHIF when Cine play is activate.
=> Setting a default value for resetPrefetchDelay

src/imageTools/annotation.js, src/imageTools/seedAnnotate.js, src/imageTools/textMarker.js
jquery stops the event propagation when 'false' is returned and this can break the UI.
=> image tools: event handlers should not return 'false' when it's disabled or toolData is unavailable

src/imageTools/dragProbe.js
The user is not able to see the dragProb info because the image is being rendered asynchronously (requestAnimationFrame) and losing the info rendered by dragProbe tool.
=> fix: dragProbe tool

src/stackTools/scrollIndicator.js
For mobile devices it would be fine to have the scrollbar in a vertical left position to not hide the scrollbar by the fingers
when working with the images.
=> Make scrollbar position configurable

src/imageTools/freehand.js
When using the freehand tool, if you click to create the first handle, then shift click to freehand draw, then end the shape by clicking the origin point, the resulting annotation object will contain a circular reference within the single handle. This occurs when it tries to close the shape by appending the `handleNearby` object to the same handle's `handle.lines` array. This fix appends a new object copying just the x, y coordinates of `handleNearby`.
The circular reference doesn't cause any problems until you try to serialize the annotations object (i.e. to save to a DB). Both` jQuery.extend()` and `JSON.stringify()` will throw errors.
=> Prevent circular reference when single handle

src/imageTools/touchTool.js
It is not possible at the moment to make touch tools interactive but not creatable.
The 'CornerstoneToolsTouchStart' should be set to on if the tools is deactivated.
When a measurement is modified the 'CornerstoneToolsTouchStart' event should be used instead of the 'CornerstoneToolsTouchStartActive' to not enable the creatation of new objects
=> Bugfix for interactive mode in touch tools

src/inputSources/mouseInput.js
Variable is not initialized, so the first click event is not send
=> Bugfix for 'CornerstoneToolsMouseClick'

src/inputSources/mouseWheelInput.js
Without `e.preventDefault()` the page would still scroll when using the wheel over the canvas
=> Stop scrolling the page

src/stateManagement/stackSpecificStateManager.js
I'm adding a stack specific tool, but even though some examples show usage like:
`cornerstoneTools.addStackStateManager(element, ['stack', 'playClip']);`
the second argument is never used, the function itself has a hardcoded list of tools.
This pull request simply merges the second argument into the list of tools.
=> Concat custom tools into stack specific state manager

src/.gitattributes, src/stackTools/stackPrefetch.js, src/util/getMaxSimultaneousRequests.js
Fix the circular dependency in getMaxSimultaneousRequests.js (see https://github.com/chafey/cornerstoneTools/issues/215)
Added a setMaxSimultaneousRequests called from stackPrefetch.js and removed importing stackPrefetch from getMaxSimultaneousRequests.js
Also added .gitattributes to prevent windows/unix cr/lf mismatch
=> Fix circular dependency

src/manipulators/moveNewHandle.js
This PR closes https://github.com/chafey/cornerstoneTools/issues/217
The highlight issue occurred whenever a new annotation was created, all other annotations would not be highlighted when moved over.
=> Fix for https://github.com/chafey/cornerstoneTools/issues/217 

src/stackTools/playClip.js
Stopping the clip does not stop promises which are in progress, so it sometimes completes loading the image after user displays another series in the viewport. In this case, it cannot find the previous enabled element when the image is loaded, so it throws an exception. This is a quick solution by ignoring the exception, but there might be a better solution which stops the promises that are in progress when the clip is stopped.
=> Ignore the exception thrown when the image is loaded by playClip

src/imageTools/length.js
Measurements wasn't working on some images due to undefined `imagePlane.colPixelSpacing`, replaced to `imagePlane.columnPixelSpacing`.
=> replaced imagePlane.colPixelSpacing with imagePlane.columnPixelSpacing

src/stackTools/stackScroll.js
This PR fixes touch scrolling for large image sets.
The previous behaviour led to scrolling more than 1 image per pixel if there were more images than the height of the element in pixels, which wasn't a good user experience.
New behaviour is to scroll at most 1 image per 2 pixels, and at least 1 image per 1/8 of the element height.
=> fix stackscrolling with touch on large image sets

src/stackTools/stackPrefetch.js
Adds a new configuration option to the stack prefetch tool, allowing it
to only prefetch the closest X images, where X is 10 as default. It
significantly improves the stability of prefetching when limiting the
cache size.
=> feat(prefetch): add a maximum number of images to prefetch

examples/exampleMetaDataProvider.js, examples/exampleNumberMetaDataProvider.js, examples/layeredImageStacks/index.html, examples/orientation/index.html, examples/petctMetaDataProvider.js, src/imageTools/crosshairs.js, src/imageTools/length.js, src/imageTools/orientationMarkers.js, src/referenceLines/renderActiveReferenceLine.js, src/synchronization/Synchronizer.js, src/synchronization/stackImagePositionOffsetSynchronizer.js, src/synchronization/stackImagePositionSynchronizer.js
This is part of a "bug" fix for https://github.com/chafey/cornerstoneTools/issues/242
(Really more of a small update to remain consistent)
The other half is adding the fields required for the reference line tool to work to the WADORS/WADOURI image loaders. You can find a working implementation on the OHIF viewer:
https://github.com/OHIF/Viewers/blob/de5fe8d5346481c534234865f00c70f41403c31a/Packages/ohif-cornerstone/client/lib/classes/MetadataProvider.js#L249-L259
*Missing fields for WADORS:*
- frameOfReferenceUID
- rowCosines
- columnCosines
*Missing fields for WADOURI:*
- rowCosines
- columnCosines
I probably didn't miss anything. Cheers, @swederik
=> Examples updated to use same naming as cornerstoneWADOImageLoader

src/stackTools/stackScroll.js, src/util/scroll.js
I wanted a way to consume scroll events and prevent the stack state from progressing to the next index until the currently request index had been drawn. I *think* this covers that.
=> Add configuration and functional option to scroll a stack without skipping images

src/stackTools/stackScroll.js
Fix for Issue #338.
Both _stackScroll_  & _stackScrollTouchDrag_ were using the same _toolName_ for setting _options_. 
This was creating a condition of _options_ being overridden.
=> Bug when activating stackScroll before stackScrollTouchDrag at the same time. #338

src/imageTools/freehand.js
This is a bug fix on freehand tool. 
**Issue:** 
Once the user modify the first point in the ***, the line between the first and the second element stays stuck in the first position. 
**Root cause:** 
After modifying the first point, we were trying to update the line in the point-index decremented by 1, but as the first its 0, we should be updating the last in the sequence instead. 
**Fix:** 
Once we update the line, we verify if the currentHandle (point index) is 0, and if it is, we use the last in the sequence instead. 
**Notes:** 
The author removed the if condition we had to check the currentHandler, I kept this because I don't see any part in the code that we remove it and its part of the default value of the configuration object. 
**Tests:** 
I have done tests on Chrome65 and it was …
=> Fix freehand edit first point

src/imageTools/ellipticalRoi.js, src/imageTools/rectangleRoi.js
This PR is an Improvement in the ROI Tools to start using pixelSpacing when present in the metaData
Tests: 
I have tested both elliptical and rectangle calculations and everything is working fine.
=> Use pixelSpacing from MetaDataProvider in ROI tools

changelog.md, src/imageTools/freehand.js, src/util/calculateFreehandStatistics.js, src/util/freeHandArea.js, src/util/freeHandIntersect.js, src/util/pointInFreehandROI.js
Improvements and new functionalities
New functionalities:
- Added general area calculation for irregular polygons of N sides.
- Added textbox to show data from the area of the polygons of N sides, it does not affect 'pencil' mode 
- The textbox-polygon tether snaps to nearest node of the polygon when moved.
Improvements:
- Disallows the user to join up to any previous point besides the starting node (i.e. shape must be complete before tool deactivates).
- Disallows the user to cross lines (using a orientation algorithm).
Tests: 
All the old functionalities and the new ones are working fine.
=> Free hand improvements

config/webpack/webpack-base.js, config/webpack/webpack-prod.js, package-lock.json, package.json
- Upgrade webpack to v4
- `npm start` and `npm test` working fine. 
- Examples tested
After this PR, `npm install`  is needed in the next use.
=> Upgrade Webpack to v4

changelog.md, src/imageTools/crosshairs.js
Bug fix for the crosshairs tool.
The crosshairs tool throws an exception when used with a source image that has not imagePlaneModule metadata (#385).
A security check is made for the existence of the metadata. If it does not exist, now it doesn't do anything (simply `return`s the function).
No.
=> Prevents error on crosshairs when image has no imagePlaneModule

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/length.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js
If tool data has the `visible` flag set to false, then `pointNearTool` will return false. This is to prevent mouse interaction with the tool when the data is invisible.
#387
Clicking on an invisible tool will not update the invisible tool.
No
=> fix(interaction) No tool interaction when tool is invisible

.travis.yml, src/imageTools/scaleOverlayTool.js
- Adding default config into displayTool configuration, so we can use getter and setter of it. 
- It does not change how the tool should work.
=> Persist the scaleOverlayTool default config into displayTool 

src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/length.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/util/drawLink.js
This PR adds a `drawLink` function, which captures the way we draw link lines between tools and their associated text boxes.
This change doesn't introduce any new functionality or changes to existing behaviour.
=> Update: Add a drawLink function to remove duplicated code

src/imageTools/freehand.js, src/util/calculateFreehandStatistics.js, src/util/pointInFreehandROI.js
New features:
-- Refactored the create functionality into the MOUSE_DOWN_ACTIVATE event, such that the passive functionality could be improved. The tool is now editable whilst the freehand tool is in deactivate mode (i.e. whilst another tool is being used).
-- Editing nodes of the polygon now works based on drag-release rather than click-move-click, as this feels more intuitive.
-- If a drag edit would create a non-simple polygon, the node snaps back to its previous position.
Bug fixes:
-- My statistic features where re-factored by another user when I submitted my last pull request, and a bug was introduced (currently in master branch), whereby statisticsObj.count was global and recalculation due editing the polygon would lead to shrinking erroneous results. This is now fixed.
=> Freehand Update: drag to edit, passive functionality and bug fix for statistics

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/length.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js, src/stateManagement/toolColors.js
This change adds a `.color` attribute to the tool data for those tools which currently have a `.active` attribute. If `.active` is true and `.color` is defined, then the tool data will be displayed using the custom color. If `.active` is true and `.color` is undefined then the tool data will be displayed using the default active color (`activeColor`). If `.active` is false, then the default tool color (`white`) will be used.
This is my first contribution to the project, so please advise if this change is not appropriate or could be achieved in a better way.
This PR partially address the backlog item from `README.md`: 
> Config object that allows tool appearance to be customized (e.g. line color, text color, handle size, shape, etc)
=> Feature: Add a .color attribute to the tool data

src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/length.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/util/drawLinkedTextBox.js
The new `drawLinkedTextBox` consolidates common code for drawing a text box which is linked to an image tool.
This PR also introduces the `textBoxAnchorPoints` function to each appropriate image tool, which abstracts out the code for computing possible anchor points for the link to the text box.
=> Add a drawLinkedTextBox function

src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/length.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js
Moving the code for generating the text box text into a separate function for each tool reduces the complexity of the `onImageRendered` function and also makes the common patterns across tools more obvious.
My aim with this collection of refactorings is to have the `onImageRendered` for each tool follow the same template, with the tool-specific details factored out into separate functions (like `textBoxText`).
The motivation here is to make it simpler to maintain our own custom tools.
=> Add a textBoxText function to all tools which use drawLinkedTextBox

src/imageTools/length.js
Row and column pixel spacing were switched
Bug fix
If row pixel spacing is not the same as column pixel spacing, distances aren't correctly calculated
Distances are calculated correctly
No
=> Fix x and y distances

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/dragProbe.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/imageStats.js, src/imageTools/length.js, src/imageTools/magnify.js, src/imageTools/orientationMarkers.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js, src/imageTools/scaleOverlayTool.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js, src/stackTools/scrollIndicator.js, src/util/drawing.js
This PR uses the `getNewContext()` function in all places where we need a `context` object.
There is one exception, in [`referenceLinesTool.js`](https://github.com/cornerstonejs/cornerstoneTools/blob/3e587198a6d1038cb3c1a240d1e6906cf2214536/src/referenceLines/referenceLinesTool.js#L25). This function does not follow the pattern of creating a `context` and immediately settings the identity transform. Refactoring this particular use case will be left for a future task, and may involve modifying either the behaviour of this tool.
See #405 for full discussion
=> [2/N] Use the getNewContext() function from drawing.js

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/dragProbe.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/length.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js, src/imageTools/scaleOverlayTool.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js, src/imageTools/wwwcRegion.js, src/paintingTools/drawBrush.js, src/referenceLines/renderActiveReferenceLine.js, src/stackTools/scrollIndicator.js, src/timeSeriesTools/probeTool4D.js, src/util/drawTextBox.js
This PR replaces calls to `context.save()` and `context.restore()` with calls to the `draw()` function from the `drawing.js` API.
In some cases in the existing code, there would be a `return` or `continue` statement between the calls to `context.save()` and `context.restore()`. The logic for this flow control has been shifted outside the `draw()` function to ensure that we don't have calls to `context.save()` which never call `context.restore()`.
See #405 for full discussion
=> [3/N] Use the draw() function from drawing.js

config/webpack/webpack-dev.js, config/webpack/webpack-prod.js, package-lock.json, package.json
Add webpack-dev-server and hot reloading for development
Adds webpack-dev-server for hot reloading while doing development on the Examples
We don't have any hot-reloading, so we need to manually refresh.
Hot reloading and web serving for the examples. It also adds an index.html to the top-level of the repository so that the dev server / Netlify links do not 404.
No
* **Other …
=> feat(dev-server) Add webpack-dev-server and hot reloading for development

src/imageTools/zoom.js
Small change to address #296. 
Now inverting the config changes how zoom behaves on mouse drag events, in addition to mouse wheel events.
=> Added invert option to zoom with mouse drag

src/imageTools/angleTool.js, src/imageTools/dragProbe.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/length.js, src/imageTools/rectangleRoi.js, src/imageTools/scaleOverlayTool.js, src/imageTools/simpleAngle.js, src/imageTools/wwwcRegion.js, src/manipulators/drawHandles.js, src/referenceLines/renderActiveReferenceLine.js, src/timeSeriesTools/probeTool4D.js, src/util/drawArrow.js, src/util/drawCircle.js, src/util/drawEllipse.js, src/util/drawLink.js
This PR replaces calls to `context.beginPath()` and `context.stroke()` with calls to the `path()` function from the drawing.js API.
=> [4/N] Use the path function from drawing.js

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/dragProbe.js, src/imageTools/ellipticalRoi.js, src/imageTools/length.js, src/imageTools/rectangleRoi.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js, src/imageTools/wwwcRegion.js
This PR replaces blocks of code setting the `context` shadow parameters with calls to the `setShadow()` function from the `drawing.js` API.
=> [5/N] Use the setShadow function from drawing.js

src/imageTools/angleTool.js, src/imageTools/freehand.js, src/imageTools/length.js, src/imageTools/simpleAngle.js, src/referenceLines/renderActiveReferenceLine.js, src/util/drawArrow.js, src/util/drawLink.js
This PR replaces calls to `path`, `moveTo` and `lineTo` with calls to `drawLine`, `drawLines`, and `drawJoinedLines` from the `drawing.js` API.
=> [6/N] Use the drawLine, drawLines and drawJoinedLines functions from drawing.js

examples/allImageTools/index.html
Bug fix
All image tools example has a console error when used from github because cornerstoneTools.eraser isn't in version 2.3.7. Causes no tools to work on this example.
The eraser tool is removed. No more console error.
No.
feeling a bit 🐑 ish
=> comment out the eraser code because its not in 2.3.7

src/imageTools/magnify.js, src/paintingTools/drawBrush.js, src/stackTools/scrollIndicator.js, src/util/drawTextBox.js
This PR replaces calls to `fillRect()` and `fillText()` with calls to the `fillBox()` and `fillTextLines()` functions from the `drawing.js` API.
=> [7/N] Use the fillBox and fillTextLines functions from drawing.js

src/imageTools/dragProbe.js, src/manipulators/drawHandles.js, src/util/drawCircle.js
This PR replaces calls to `.arc()` with calls to the `drawCircle()` function from the drawing.js API.
=> [8/N] Use the drawCircle function from drawing.js

src/imageTools/highlight.js, src/imageTools/rectangleRoi.js, src/imageTools/wwwcRegion.js
This PR replaces calls to `context.rect()` with calls to the `drawRect()` function from the drawing.js API.
=> [9/N] Use the drawRect function from drawing.js

src/util/drawEllipse.js
This PR uses the `drawEllipse` function from the `drawing.js` API within the deprecated `drawEllipse.js`.
=> [12/N] Use the drawing.js version of drawEllipse in the deprecated drawEllipse

src/imageTools/highlight.js, src/util/drawing.js
This PR adds a `fillOutsideRect` function to the `drawing.js` API. It fulfils the use case of needing to fill the entire canvas, with the exception of a particular rectangle bounded by two points. This use case comes up in `highlight.js` where most of the image is dimmed out, leaving the selected window highlighted.
This extends the API described in #405.
=> [11/N] Add fillOutsideRect function to drawing.js API

src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/dragProbe.js, src/imageTools/length.js, src/imageTools/orientationMarkers.js, src/imageTools/probe.js, src/imageTools/seedAnnotate.js, src/imageTools/simpleAngle.js, src/imageTools/textMarker.js, src/timeSeriesTools/probeTool4D.js, src/util/drawTextBox.js
This PR adds a `textBoxWidth` function to `drawTextBox.js`. It abstracts away the common operation of determining how wide the textbox needs to be for a given text and padding.
This change also ensures that the width is calculated in terms of the currently selected font. Some tools did not previously do this and could potentially calculate the wrong value if the default font of the `context` was different to the font specified in `textStyle` (although I suspect this is a fairly rare situation).
This change also allows us to avoid setting `context.font` within each tool, as all the fonts are now managed by helper functions. We also remove setting of `context.fillStyle`, since the `drawing.js` API handles this for us.
Computing the text width with explicit reference to the `padding` brings …
=> Add a textBoxWidth function

src/synchronization/Synchronizer.js, test/synchronization/panZoomSynchronizer_test.js
The default behavior of Synchronizers is unchanged.
Toggling the _enabled_ boolean on a Synchronizer instance toggles the synchronization, so that one can easily desynchronize viewers without having the need to remove all viewers from its scope.
Related to issue #464
=> Added a setting to deactivate synchronizers.

src/eventDispatchers/touchToolEventDispatcher.js, src/manipulators/getHandleNearImagePoint.js
The previous implementation incorrectly set `moveableHandle` to a set of toolData. This updates the implementation to find the `moveableHandle` within the returned toolData
=> Fix: able to grab tools by handles w/ touch

src/eventDispatchers/mouseEventHandlers/mouseDown.js, src/eventDispatchers/mouseEventHandlers/mouseMove.js, src/store/index.js
I'll tag you as a reviewer when I wrap up @JamesAPetts 
- [Specialty Tools](https://github.com/dannyrb/cornerstoneTools/blob/4e24873ed15e330a220ed5e206cb1e1c4d021aa9/src/eventDispatchers/mouseEventHandlers/mouseDown.js#L43-L59) take priority over other tools; they can choose to `preventPropagation` if they'd like
- For AnnotationTools, [we first check handles](https://github.com/dannyrb/cornerstoneTools/blob/4e24873ed15e330a220ed5e206cb1e1c4d021aa9/src/eventDispatchers/mouseEventHandlers/mouseDown.js#L63-L88):
- Which tools have handles near our point?
- Which tool should we use? (For now, first one in array)
- Use `mouseDownCallback` if it's defined, or `handleMover`
- Then [we check PointNearTool](https://github.com/dannyrb/cornerstoneTools/blob/4e24873ed15e330a220ed5e206cb1e1c4d021aa9/s …
=> [WIP] Feature:freehand dispatcher changes

examples/freehandRoi/index.html, src/imageTools/freehand.js
Fix for #498 for current master branch.
Fixed an issue that caused mouse clicks outside the freehand tool's mask to be consumed on mouseDownCallback & mouseDownActivateCallback.
=> v2 - Freehand tool mask issue fix (issue #498).

examples/icon-classes.css, examples/icons/mouse-left.svg, examples/icons/mouse-middle.svg, examples/icons/mouse-right.svg, index.html, src/eventDispatchers/mouseEventHandlers/mouseDown.js, src/eventDispatchers/mouseEventHandlers/mouseDownActivate.js, src/eventDispatchers/mouseEventHandlers/mouseDrag.js, src/eventDispatchers/touchEventHandlers/touchStartActive.js, src/eventListeners/mouseEventListeners.js, src/index.js, src/tools/arrowAnnotateTool.js, src/util/isMouseButtonEnabled.js
This addresses:
- CC: @swederik 
- Which means you can now bind tools, to some extent, to multiple buttons needing to be pressed for their strategies to be applies
- IE. back/forward mouse buttons on fancier mice
Also touched:
=> MouseEvent.buttons to replace MouseEvent.which; and auto-tool `passive`

src/imageTools/arrowAnnotate.js
- Arrow Annotate was not calling the modified event after updating its own text.
=> ArrowAnnotate: Trigger modified after text change

changelog.md, src/stackTools/stackPrefetch.js
Currently, switching to a viewer with a stack prefetch tools removes all existing prefetch requests.
By changing a boolean value, this is no longer the case.
Solves issue #529
`config = cornerstoneTools.stackPrefetch.getConfiguration();
config.preserveExistingPool = true;`
Please note that the build is currently K.O. but was before my commit.
=> Added a configuration to allow for prefetching to keep the existing pool

src/paintingTools/brush.js, src/paintingTools/brushTool.js, src/paintingTools/fill.js, src/paintingTools/queue.js
I've implemented fill inside of segmentation with brush tools.
In the case of the closed space first, double-clicking will color the region.
If it is not a closed space, it will be colored by connecting both ends.
Please refer to attached images.
=> Add fill the region of brush tool

src/store/brushStore.js, src/tools/CrosshairsTool.test.js, src/tools/EllipticalRoiTool.test.js, src/tools/FreehandMouseTool.test.js, src/tools/LengthTool.test.js, src/tools/PanMultiTouchTool.test.js, src/tools/PanTool.test.js, src/tools/ProbeTool.test.js, src/tools/RectangleRoiTool.test.js, src/tools/RotateTool.test.js, src/tools/ScaleOverlayTool.test.js, src/tools/StackScrollMouseWheelTool.test.js, src/tools/StackScrollTool.test.js, src/tools/WwwcRegionTool.test.js, src/tools/WwwcTool.test.js
- Make sure that external.cornerstone.colors exist before using 
- It will avoid breaking unit tests that does not mock this functions and also we can remove a lot of mock functions inside unit tests that are not being tested directly. 
NOTE: In case we want to test the colors/colorMap from Brush, we can mock the function inside the unit test and perform the tests desired.
=> Refactor brushStore and unit tests

.eslintrc.js
- Adding 'valid-jsdoc' attribute into eslint in order to warn once a new file/function is missing a jsdocs.
=> Adding back eslint validation on jsdocs

src/events.js, src/imageTools/displayTool.js, src/imageTools/dragProbe.js, src/imageTools/freehand.js, src/imageTools/freehandSculpter.js, src/imageTools/magnify.js, src/imageTools/mouseButtonRectangleTool.js, src/imageTools/mouseButtonTool.js, src/imageTools/scaleOverlayTool.js, src/imageTools/touchTool.js, src/imageTools/wwwcRegion.js, src/paintingTools/brushTool.js, src/referenceLines/referenceLinesTool.js, src/stackTools/stackPrefetch.js, src/synchronization/Synchronizer.js, src/util/scroll.js
- Remove events from cornerstone-core from cornerstoneTools event list. 
- Use events direct from cornerstone-core library. 
(Closes #369)
=> Use cornerstone events directly from  its own lib

src/eventDispatchers/shared/customCallbackHandler.js, src/eventDispatchers/touchEventHandlers/touchStart.js, src/eventDispatchers/touchEventHandlers/touchStartActive.js
Bug fix
If there are multiple active tools with different button masks, in touch it won't be able to filter the current tool and will activate the first one in the list.
A new option was added (touchEnable) and touch tools are filtered by this option. If it's false it won't be an active tool. 
=> Add filter for touch tools

src/tools/FreehandMouseTool.js
Fixes a breaking issue that occurs when one attempts to switch tool half way through drawing a freehand ROI.
=> vNext - Fix freehand active drawing edge case

package.json, src/imageTools/freehand.js
Fixes a breaking issue that occurs when one attempts to switch tool half way through drawing a freehand ROI, by auto-completing the ROI before switching.
=> v2 - Fix freehand active drawing edge case

src/synchronization/stackImagePositionOffsetSynchronizer.js, src/synchronization/stackImagePositionSynchronizer.js
The `stackImagePositionSynchronizer` and `stackImagePositionOffsetSynchronizer` were both using `cornerstone.getEnabledElement(sourceElement).image.imageId`.  When these synchronizers are called, that image has not yet been updated from the scroll event, which means all the distance calculations are done against the previous image.
Getting the source `imageId` via the stack data `getToolState(sourceElement, 'stack').data[0]` (the same way the _target_ `imageId` is retrieved later) gives us the correct image because the stack's `currentImageIdIndex` has already been updated when this is called.
=> Fix image position synchronizers using previous source image

src/tools/FreehandMouseTool.js, src/tools/FreehandSculpterMouseTool.js
Based on a combination of some recent feedback and in the interest of keyboard clutter, both the `FreehandMouseTool` and the `FreehandSculpterMouseTool` no longer use modifier keys.
`FreehandMouseTool`:
- Polygon and and Pencil modes are now baked into user input rather than activating with a modifier key. You can also freely switch between the two whilst drawing the ROI.
- Dragging with the mouse uses pencil mode.
- click -> move -> click -> ... allows you to place points manually (polygon mode).
`FreehandSculpterMouseTool`:
- When first activated, with no ROI selected, clicking/double-clicking near an ROI will make it the subject.
- You can change subject ROI by double-clicking near a new subject.
- Sculpting your subject ROI works as before.
=> vNext Freehand UX

src/tools/MagnifyTool.js
fixes #634 
After using Magnifying glasses once no tool work anymore
Magnifying can be used multiple time and any other tool too
NO
=> fix: disable zoomCanvas instead of zoomElement, avoid events to be unbound

src/tools/DragProbeTool.js
Prior to this PR it would attempt to render every frame, even if you aren't using the `DragProbeTool`.
=> Fixed dragProbeTool issues.

src/tools/MagnifyTool.js
- Constrain magnifier position to keep it within the canvas (not off-screen or potentially behind other elements)
- Shrink magnifier to fit in canvas if canvas width or height is smaller than default `magnifySize`
- Constrain `canvasLocation` to keep it within the zoomed image boundaries (no transparent areas in magnifier)
The `clipToBox`, `fillBox`, and `getBrowserInfo` helpers were then no longer needed.
=> Keep magnify tool's magnifier inside the canvas

src/imageTools/angleTool.js, src/imageTools/pan.js, src/util/pointProjector.js
fixes 
https://github.com/cornerstonejs/cornerstoneTools/issues/645
make sure rowPixelSpacing and colPixelSpacing default to 1 if null before being used in divisions etc ..
=> bugfix defaulting rowPixelSpacing and colPixelSpacing to 1

src/lib.js
exposes `findAndMoveHelpers.js` through the import lib.
=> vNext - expose findAndMoveHelpers

src/eventListeners/windowResizeHandler.js, src/init.js
This PR patches the `init` method
- Make sure we remove any lingering listeners before adding new ones
- Update `windowResizeHandler`'s `disable` method to remove the event listener (previously added)
=> Fix: Calling `init` multiple times should not leave lingering listeners

src/eventListeners/windowResizeHandler.js, src/store/internals/removeEnabledElement.js
- fix export of force resize method
- fix tool filtering logic that fires when an enabled element is `disabled`
=> Fix: export mistake, `elementDisabled` tool filtering logic

src/manipulators/getHandleNearImagePoint.js, src/store/getToolsWithMoveableHandles.js
- Before: Tool handles had to be an object of named handles
- After: Tool handles can be an object of named handles, an array of handles, or an object of named handles and named arrays that contain handles
=> Feature: Expand supported schema for tooldata's handles

src/eventDispatchers/mouseEventHandlers/mouseDown.js, src/eventDispatchers/touchEventHandlers/touchStart.js
This likely broke in a merge or when we converted to using our more complex `is${interactionType}Active` checks.
=> Fix: broken passive tool handle manipulation

src/eventDispatchers/touchEventHandlers/index.js, src/eventDispatchers/touchEventHandlers/multiTouchDrag.js
- Check the numPointers to get the first activated tool for interaction. 
Solve issues when we have Pan on two-fingers and Stackscroll with three-fingers.
=> fix(MultiTouch): Tools with different touchPointers activated at the same time

src/tools/annotation/bidirectionalTool/moveHandle/moveHandle.js, src/tools/annotation/bidirectionalTool/moveHandle/perpendicularBothFixedLeft.js, src/tools/annotation/bidirectionalTool/moveHandle/perpendicularBothFixedRight.js, src/tools/annotation/bidirectionalTool/moveHandle/perpendicularLeftFixedPoint.js, src/tools/annotation/bidirectionalTool/moveHandle/perpendicularRightFixedPoint.js, src/tools/annotation/bidirectionalTool/moveHandle/setHandlesPosition.js, src/tools/annotation/bidirectionalTool/moveHandle/touchMoveHandle.js
- Updates logic for movement of bidirectional tool handles, so that they don't snap to the location of the pointer that grabbed them
- When you move the bidirectional tool's handles, the handle snaps to the mouse / finger location which makes it very hard to use on touch devices
- The original displacement between the pointer and the handle is maintained while the handle is moved.
- No
* …
=> fix(bidirectional): Fix movement of handles for bidirectional tool

src/util/drawing.js
import toolStyle and textStyle from where they are defined instead of index.js
=> Prevent circular import dependency

src/imageTools/probe.js
This PR hotfixes issue #693. It does not solve the underlying problem which is the call to getRGBPixels in the draw function of the probe tool(After investigating a while with firefox perfomance tool).
The current behavior makes the canvas too unresponsive if the amount of probes is larger than ~5 (See #693.) 
The new behavior is that the text box is not drawn and that makes the page more responsive if the textbox is not desired.
Users do not …
=> Feature to disable probe textbox by setting the configuration. 

config/webpack/webpack-base.js, package.json, src/index.js, src/store/modules/brushModule.js, src/tools/base/BaseTool.js
- Updates the webpack entry point and library output config to match the other Cornerstone libraries
- Switches the NPM 'module' to point to the built library
- Adds a top-level named (default) export named cornerstoneTools
Users must use `import * as cornerstoneTools from 'cornerstone-tools'` which is unconventional.
- Users can use `import cornerstoneTools from 'cornerstone-tools'`
- …
=> chore(exports): Try to add a top-level export named cornerstoneTools

src/imageTools/eraser.js
`Bugfix` -- a filter was added to the eraser tool. This filter is necessary because it's causing a bug when trying to assign LMB to length (for example) and RMB to eraser.
**Linked issue**: https://github.com/cornerstonejs/cornerstoneTools/issues/695
**Codepen**: https://codepen.io/anon/pen/eQMpxx
A filter was added to eraser tool event, avoiding it to be triggered when it shouldn't.
No. …
=> Adds a filter to Eraser mouse events

src/eventListeners/onNewImageBrushEventHandler.js
The brush layer would previously flicker when quickly scrolling through a large image. This was due to clearing the brush layer cache on a new image. This change makes it so that the previous mask is rendered until the new mask is loaded (typically ~1 frame). This lag isn't noticeable, and it much more visually pleasing then the flickering that occurred previously.
=> Fix flickering of brush canvas.

src/drawing/index.js, src/drawing/resetCanvasContextTransform.js, src/drawing/transformCanvasContext.js, src/eventListeners/onImageRenderedBrushEventHandler.js, src/tools/annotation/EllipticalRoiTool.js, src/tools/brush/BrushTool.js
This PR solves (in part) #579 . This PR makes it such that the brush mask is correctly orientated in relation to the `cornerstone` canvas, should the `viewport` be rotated or flipped. This works for arbitrary rotations, not just 90 degree rotations. The image can still be drawn on whilst in an arbitrarily transformed state.
This PR does not address the issues that the ellipse or rectangle tools exhibit when rotated by a non 90-degree rotations.
=> vNext - Correctly transform brush canvas

src/imageTools/angleTool.js
solves issue https://github.com/cornerstonejs/cornerstoneTools/issues/762
The recent version of `angleTool.js` changed to use `drawJoinedLines` which is wrong for cobbs angle (where the lines  are not joined).
This PR uses `drawLines` instead which gives the desired result.
=> Fix broken cobbs angle

index.html, src/store/index.js
This fixes the `getEnabledElementByUID` getter in the store. It was originally checking the DOM elements for the `cornerstone` uuid, whereas it should have been checking the `cornerstone` `enabledElement`.
=> vNext - Fix store.getters.enabledElementByUID.

src/manipulators/moveAllHandles.js, src/manipulators/moveHandle.js, src/manipulators/moveNewHandle.js, src/tools/annotation/EllipticalRoiTool.js, src/util/calculateSUV.test.js, src/util/debounce.js, src/util/ellipse/index.js, src/util/isObject.js, src/util/throttle.js
- ROI calculations were not populated on first placement
- Calculations were only invalidated on `upHandler` for `moveAll` or `moveHandle`
- Misc. performance and code smell issues
- Update `moveAllHandles`, `moveHandle` and `moveNewHandle` to invalidate annotation data when appropriate
- Break `EllipticalRoi` code into smaller, composable methods
- Add calculation throttling (`110 ms`) to improve performance
- Slipped in the ability to toggle on additional stats about the ellipse
- Slipped in the ability to toggle `HU` as a unit for `CT` images
- Set throttling w/ configuration
- Set unit as `mm` or `cm`
- Configurable `manipulator` to not invalidate when only a textbox has been moved
- Update documentation
- More unit tests <3
=> Elliptical touch-up

.eslintrc.js, examples/freehandRoi/index.html, src/imageTools/freehand.js
Freehand example updated to show the feature.
Fix freehand tool doesn't fire MEASUREMENT_MODIFIED event #774 and include area statistics on completion.
The cornerstonetoolsmeasurementmodified is not fired from the freehand tool
The cornerstonetoolsmeasurementmodified gets fired and when drawing completed the event will contain the measurement data
No
=> Fix freehand tool doesn't fire MEASUREMENT_MODIFIED event #774 

examples/freehand/index.html, src/tools/FreehandSculpterMouseTool.js, src/tools/annotation/FreehandMouseTool.js
Updated freehand example
This PR fixes the issue described here:
Freehand handles not closed after loading state data #775
Also, another issue has been fixed that is caused by mixing the freehand "handles" as an Array type and an Object type at the same time causing the serialization of the handles array to lose the object data fields "textBox", "start"... once serialized.
The "handles" has been changed to be an object which contains a separate field called "dataHandles" of type Array.
Finally, although the freehand now can be saved/loaded successfully, the save using JSON.serialize will fail if the sculpture tool is applied on the freehand …
=> Fix saving and loading the freehand moust tool. Issue # 775 for v3

src/tools/OverlayTool.js
Our `viewport` pixel spacings can be null, which results in a `0` width/height for the `layerCanvas`, which causes an exception.
We can either bail out early, or assume a `1:1` pixelSpacing in  this situation
=> Protect against `null` viewport pixelSpacing

src/tools/FreehandSculpterMouseTool.js, src/tools/annotation/FreehandMouseTool.js, src/util/freehand/addLine.js, src/util/freehand/index.js, src/util/freehand/insertOrDelete.js
The FreehandMouseTool and `FreehandMouseSculpterTool` now use spacing based on image coordinates, rather than the canvas. Thus the `FreehandMouseSculpterTool` no longer adds a load of points if zoom right in and sculpt.
Additionally new points are only added to the region being sculpted. This improves performance and reduces the number of superfluous points.
=> feat: Updates the freehand suite to use spacing in image coords.

src/eventListeners/onImageRenderedBrushEventHandler.js, src/eventListeners/onNewImageBrushEventHandler.js, src/tools/base/BaseBrushTool.js, src/tools/brush/BrushTool.js
re #834
Now labelmaps are only added to the slice when they are drawn. If you try to erase a labelmap that doesn't exist it now doesn't insert a blank one. This improves performance when stack scrolling through a new set of images, as the memory for the labelmaps is now only allocated when you begin drawing.
=> Allocate labelmap memory on demand rather than on image load.

examples/allImageTools/index.html, src/events.js, src/imageTools/angleTool.js, src/imageTools/arrowAnnotate.js, src/imageTools/ellipticalRoi.js, src/imageTools/freehand.js, src/imageTools/highlight.js, src/imageTools/length.js, src/imageTools/mouseButtonRectangleTool.js, src/imageTools/mouseButtonTool.js, src/imageTools/probe.js, src/imageTools/rectangleRoi.js, src/imageTools/simpleAngle.js, src/imageTools/touchTool.js, src/util/getColRowPixelSpacing.js, src/util/triggerMeasurementCompletedEvent.js
Updated the example AllImageTools
Introduce a new measurement event "cornerstonemeasurementcompleted" that is fired for the following tools:
1. Angle Tool
2. Arrow Annotate
3. Elliptical ROI
4. Freehand
5. length
6. Probe
7. Rectangle ROI
8. Simple Angle
9. Angle Tool
No such event exists. No way to tell when a user completes drawing the measurement/annotation.
1. An event "cornerstonemeasurementcompleted" is fired once the user completes drawing/moving the annotation.
2. When this event is fired, the tool …
=> Add measurement completed event #787

src/tools/brush/BrushTool.js, src/util/brush/drawBrush.js
- When you erase pixels from a `pixelData` mask, the `pixelData` memory is now freed up if you erase the last pixel of that mask on the slice.
- This is also makes it easier for tools like `dcmjs` to just hoover up all the slices that have non-blank masks on them.
- Fixed a small UI flicker edge case with the brush `imageBitmapCache`.
=> Brush memory improvements + bug fix.

src/stateManagement/imageIdSpecificStateManager.js, src/stateManagement/imageIdSpecificStateManager.test.js, src/stateManagement/toolState.js
Bug fix + some clean up of variable naming in this file
Calling  `addImageIdSpecificToolState` would throw if `element.image` did not exist.
`addImageIdSpecificToolState` will exit early if element.image does not exist.
No
=> Bugfix in image id specific state manager

src/tools/FreehandSculpterMouseTool.js
Fixed a bug where the `FreehandSculpterMouseTool` would break when used if there is no freehand annotation on the slice.
=> FreehandSculpter bug fix.

src/drawing/drawEllipse.js, src/drawing/drawRect.js, src/tools/annotation/EllipticalRoiTool.js, src/tools/annotation/EllipticalRoiTool.test.js, src/tools/annotation/RectangleRoiTool.js, src/tools/annotation/RectangleRoiTool.test.js, src/util/pointProjector.js
* **What kind of change does this PR introduce?** Bug fix
* **What is the current behavior?** https://github.com/cornerstonejs/cornerstoneTools/issues/579
* **What is the new behavior (if this is a feature change)?** Bug fix, correct rotation
* **Does this PR introduce a breaking change?** No
=> Fix issue 579

src/tools/annotation/FreehandMouseTool.js
Bug fix
Freehand passes only measurement data on measurement modified event
Pass event data in the same format with other tools on measurement modified event for freehand
Users who already handle measurement modified event for freehand need to update the data passed
=> fix(freehand): Pass event data on measurement modified event of freehand tool

src/tools/base/BaseBrushTool.js
prevents a crash when _repeatGlobalToolHistory replays setting tool mode passive for brush tools
fix #924
Bug fix
Crashing Bug: using the Brush tool with `globalToolSyncEnabled` can cause the application to crash when a new element is enabled.
- `_repeatGlobalToolHistory` replays all tool changes on a new element before the image is loaded
- BaseBrushTool calls `cornerstone.updateImage` in it's `passiveCallback`
- `cornerstone.updateImage` will crash if the image is not loaded
Wrapped the call to `updateImage` …
=> fix(BaseBrushTool.js): prevents a crash in passiveCallback

src/tools/annotation/CircleRoiTool.js, src/tools/annotation/EllipticalRoiTool.js, src/tools/annotation/RectangleRoiTool.js
The ROI textboxes are dangerously close to the handles if you draw a shape that is shorter in height than the textbox.  This is very evident if the textboxes have a background color.
This change adds a 10px x-offset to those textboxes, which matches the x-offset already used by the Length tool (probably for the same reason?).
=> Add 10px x-offset to ROI textboxes

src/eventDispatchers/mouseEventHandlers/mouseDownActivate.js
mouseDownActivate does not check if getActiveTool returned anything before accessing a property
thereof
fix #942
FIX
`mouseDownActivate.js` throws if `getActiveTool` returns `undefined`.
Exit early if `getActiveTool` has not returned a tool.
N
=> fix(mouseDownActivate.js): fix throwing issue in mouseDownActivate

src/tools/annotation/CircleRoiTool.js, src/tools/cursors/index.js
fix #944
fix / minor feature
Adds an SVG cursor for the CircleROITool
NOTE: Ignore the colour of the cursor in this screenshot. Mac OS has done something weird in the screen capture. The cursor does not specify a custom colour.
No
=> feat(CircleRoiTool.js): Adds cursor for CircleRoiTool

src/tools/brush/BrushTool.js
When alwaysEraseOnClick is on, the brush tool will erase in both strategies. This is useful for e.g.
touch devices, or if you want to add a "delete only" brush tool to your app.
=> feat(tools/brush/BrushTool.js): configuration option alwaysEraseOnClick

src/lib.js
Change `convertVectro3` -> `convertVector3` in the lib.js exports.
Thanks @mbauskar.
=> convertVectro3 -> convertVector3

docs/latest/custom-tools/adding-mixins.md, docs/latest/custom-tools/creating-your-tool.md, docs/latest/custom-tools/event-dispatcher-callbacks.md, docs/latest/custom-tools/mode-change-callbacks.md, docs/latest/third-party-functionality/imports.md, docs/latest/third-party-functionality/item-types.md, docs/latest/third-party-functionality/tools.md, netlify-example/thirdParty/index.html, src/importInternalModule.js, src/index.js, src/tools/CrosshairsTool.test.js, src/tools/DoubleTapFitToWindowTool.test.js, src/tools/DragProbeTool.test.js, src/tools/PanMultiTouchTool.test.js, src/tools/PanTool.test.js, src/tools/RotateTool.test.js, src/tools/RotateTouchTool.test.js, src/tools/ScaleOverlayTool.test.js, src/tools/StackScrollMouseWheelTool.test.js, src/tools/StackScrollMultiTouchTool.test.js, src/tools/StackScrollTool.test.js, src/tools/WwwcRegionTool.test.js, src/tools/WwwcTool.test.js, src/tools/annotation/CircleRoiTool.test.js, src/tools/annotation/EllipticalRoiTool.test.js, src/tools/annotation/FreehandRoiTool.test.js, src/tools/annotation/LengthTool.test.js, src/tools/annotation/ProbeTool.test.js, src/tools/annotation/RectangleRoiTool.test.js, src/tools/base/BaseTool.test.js
As it is a reserved word and cause issues on different platforms.
=> vNext - Rename cornerstoneTools.import to importInternalModule

netlify-example/brush/index.html, src/eventListeners/onImageRenderedBrushEventHandler.js, src/eventListeners/onNewImageBrushEventHandler.js, src/events.js, src/stateManagement/stackSpecificStateManager.js, src/store/modules/brushModule.js, src/tools/base/BaseBrushTool.js, src/tools/brush/BrushTool.js, src/util/brush/drawBrush.js, src/util/brush/getNewBrushColorMap.js, src/util/brush/getNewColorLUT.js, src/util/brush/index.js, src/util/brush/labelmapStats.js
Hey all, this is a breaking change. I've forked the current master branch to a `vNext` that we can PR against for anything which is a breaking change, namely these PRs currently: #915, #921.
In this PR I rebuild the segmentation mask system from the ground up to solve two main issues:
- Interoperability with other libraries (e.g. [`vtkjs`](https://github.com/Kitware/vtk-js))
- Scalability for large segment counts.
During the [NAMIC Project Week 30](https://projectweek.na-mic.org/PW30_2019_GranCanaria/), a bunch of us [cornerstone devs](https://projectweek.na-mic.org/PW30_2019_GranCanaria/Projects/DICOMSEG-Cornerstone-VTKJS/) attempted to link vtkjs and cornerstone. We made some good headway with a [simple POC](https://deploy-preview-5--react-vtkjs-viewport.netlify.com/cornerstone-sync-pain …
=> vNext - Segmentation overhaul

examples/tools/stack-scroll-mouse-wheel.md
Documentation update
In the stack-scroll-mouse-wheel example, using "StackScrollMouseWheelTool" as the toolName will cause an error `Unhandled Rejection (TypeError): Cannot read property 'activeBindings' of undefined`.
By using "'StackScrollMouseWheel" instead, when copying the setup snippet, the example code will compile and run as expected without throwing any errors.
No
* **Other …
=> docs(stack-scroll-mouse-wheel): Corrected toolname in setup snippet

package.json, src/store/modules/brushModule.js, src/tools/base/BaseBrushTool.js, src/tools/brush/BrushTool.js, src/version.js
In this PR I've added support for scrolling whilst drag-painting and still making sure the segments present on each slice are indexed properly.
Whilst doing this I've seperated out the the painting logic into _startPainting` and `_endPainting` in `BaseBrushTool`, with `_paint` being the abstract method that need be implemented in the tool implementation itself (.e.g `BrushTool` in the `cornerstoneTools` core library).
This slice-by-slice indexing makes it very easy to build things such as segment deletion.
On my system, deleting a randomly sampled segmentation across 100 slices of a 512x512 CT from a labelmap, and any of its associated metadata took <40 ms.
=> vNext Brush Scroll

package-lock.json, src/util/brush/getCircle.js, src/util/brush/getCircle.test.js
- Brush would "get pixels" on the next row when trying to paint the right edge
- Brush would paint the next pixel when slightly over the center-line of a pixel
- Mostly an issue when using the 1px brush and low res images
=> Fix: off by one brush get circle

src/tools/base/BaseBrushTool.js, src/tools/brush/BrushTool.js
```js
cornerstoneTools.addTool(cornerstoneTools.BrushTool, {
name: 'Brush',
configuration: {
skipPaintForInvisibleSegmentations: true
}
})
```
Tests:
- `cornerstoneTools.store.modules.brush.state.alpha = 0`
- `cornerstoneTools.getToolState(element, 'brush').data[segIndex].alpha = 0`
- `cornerstoneTools.store.modules.brush.setters.brushVisibilityForElement(enabledElementUID, segIndex, visible)`
CC: @JamesAPetts 
Other stuff:
- Shifts duplicate `get/set` toolState check out of strategies and into `BrushTool`'s `_paint` method.
- Provides a way to prevent UX confusion of adding/removing from a segmentation while it's not visible
- Provides a way to prevent modified/completed events if we're not actually modifying brush data
=> feature(brush): add configuration option to skip paint if the segmentation is not visible (skips event calls)

src/tools/annotation/FreehandMouseTool.js
Committing this in smaller parts just to make it easier to follow the refactor as it happens. This
part just makes sure we are accessing the element and using the element in a consistent manner
throughout. Also made some small changes to other attributes that are accessed off the event data.
This is a refactor of the FreehandMouseTool to make sure we're consistently accessing the `element` associated with the event data.
No change.
No change.
* **Does this PR introduce a breaking change?** (What changes might …
=> refactor(FreehandMouseTool): Consistently access event `element`

src/tools/annotation/ArrowAnnotateTool.js
removing filters from doubleClickCallback to allow users to update text on arrowAnnotateTool
It is not possible to update the text
now it is possible to update the text
No
=> removing filters from doubleClickCallback to allow users to update text on arrowAnnotateTool

docs/latest/modules/segmentation.md, netlify-example/brush/index.html, netlify-example/metaDataProvider.js, src/mixins/segmentation/circleSegmentationMixin.js, src/mixins/segmentation/freehandSegmentationMixin.js, src/mixins/segmentation/rectangleSegmentationMixin.js, src/store/modules/segmentationModule/addLabelmap3D.js, src/store/modules/segmentationModule/configuration.js, src/store/modules/segmentationModule/getLabelmaps3D.js, src/store/modules/segmentationModule/history.js, src/store/modules/segmentationModule/history.test.js, src/store/modules/segmentationModule/index.js, src/store/modules/segmentationModule/setLabelmap3D.js, src/tools/base/BaseBrushTool.js, src/tools/segmentation/BrushTool.js, src/tools/segmentation/SphericalBrushTool.js, src/util/segmentation/drawBrush.js, src/util/segmentation/getDiffBetweenPixelData.js, src/util/segmentation/index.js
A history of undo and redo actions are stored per `labelmap3D`.
- All core tools in the lib now save a diff to the undo stack after usage (for brush tools, after the brush stroke).
- Two public methods added to the segmentation module:
- `setters.undo(element, labelmapIndex)` - Undoes one action, and adds to the redo stack. If `labelmapIndex` is not set the `activeLabelmapIndex` is used.
- `setters.redo(element, labelmapIndex)` - Redoes one action, and adds to the undo stack. If `labelmapIndex` is not set the `activeLabelmapIndex` is used.
- Diffs are calculated for each `Labelmap2D` affected, if multiple frames are affected, you just store an array of the diffs for each. This gives very simple API for all 2D tools, and 3D tools.
- Diffs poped and pushed between undo and redo stacks. The …
=> Cornerstone Tools 4.0: Undo/Redo for labelmaps.

src/eventDispatchers/imageRenderedEventDispatcher.js, src/store/modules/segmentationModule/getBrushColor.js, src/store/modules/segmentationModule/getLabelmap2D.js, src/store/modules/segmentationModule/getLabelmaps3D.js
Segmentation tools still require stacks to operate, but this fixes issues such as #1065 .
=> Fix #1065, use cornerstoneTools without stacks.

src/tools/segmentation/SphericalBrushTool.js
Pass the user defined props to super in SphericalBrushTool
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
Bug Fix
The implementation of `SphericalBrushTool` wasn't passing the user defined `props` to `super` so settings could not be overridden.
Pass props and default props to super.
n/a
* **Other …
=> fix(SphericalBrushTool.js): Consistent implementation of props and defaultProps

src/tools/FreehandRoiSculptorTool.js
The FreehandRoiSculptor tool needs to be able to reference the state of the FreehandRoiTool to modify measurements. This reference is configured via the `referencedToolName` prop. The current implementation defines this as configurable API but then uses the default value instead of the merged value.
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)
Bug Fix
The `FreehandRoiSculptor` tool uses the default `referencedToolName` instead of the result from merging `props` and `defaultProps`.
* …
=> fix(FreehandRoiSculptorTool.js): Use merged props value over default

index.html, src/tools/DragProbeTool.js, src/tools/RotateTool.js
`DragProbeTool`'s strategies were defined as arrow functions, which made them not callable with the correct context, replaced with regular function declarations.
Added `DragProbeTool` to the index.html demo under the 'drag' tab.
=> Fix DragProbeTool

src/tools/base/BaseBrushTool.js, src/tools/segmentation/BrushTool.js, src/tools/segmentation/SphericalBrushTool.js
Emit `EVENTS.LABELMAP_MODIFIED` only at the end of a brush stroke, to prevent spamming of this event.
=> EVENTS.LABELMAP_MODIFIED throttle

src/tools/ScaleOverlayTool.js
Fix override of custom line width and color for main horizontal and vertical lines of the ScaleOverlayTool.
=> fix: 🐛 Use correct configuration options for ScaleOverlayTool

src/lib.js, src/util/getKeyPressData.js
Adds a util function that consumes a native `keydown`, `keyup` or `keypress` event and returns information about the cornerstone element and the position of the mouse cursor. Useful for "do something to this hovered annotation" functions at the app level.
```
element.addEventListener('keydown', (evt) => {
console.log(cornerstoneTools.importInternal('util/getKeyPressData')(evt))
});
```
=> feat: 🎸 Adds a getKeyPressData function will

docs/latest/index.md, index.html, netlify-example/brush/index.html, src/eventDispatchers/imageRenderedEventDispatcher.js, src/eventListeners/internals/renderSegmentation.js, src/eventListeners/internals/renderSegmentationFill.js, src/eventListeners/internals/renderSegmentationOutline.js, src/eventListeners/onImageRenderedBrushEventHandler.js, src/events.js, src/init.js, src/store/modules/cursorModule.js, src/store/modules/segmentationModule/activeSegmentIndex.js, src/store/modules/segmentationModule/colorLUT.js, src/store/modules/segmentationModule/defaultConfiguration.js, src/store/modules/segmentationModule/index.js, src/store/modules/segmentationModule/setLabelmap3D.js, src/store/modules/segmentationModule/setRadius.js, src/tools/base/BaseBrushTool.js, src/tools/segmentation/BrushTool.js, src/tools/segmentation/SphericalBrushTool.js
Allows an app to pass an array of configuration to `cornerstoneTools` on `init()`.
=> Configuration for multiple modules on init.

src/lib.js
This simply exports `getROITextBoxCoords` so custom ROI tools can use it.
=> Export getROITextBoxCoords

src/tools/annotation/bidirectionalTool/addNewMeasurement.js
=> fix #1101: Updating the perpendicular line handles when done creating

src/tools/annotation/ArrowAnnotateTool.js
* **Please check if the PR fulfils these requirements**
Bug fix.
* **What is the current behaviour?** (You can also link to an open issue here)
Currently, the annotation label only updates in the measurement table if the user intentionally changes the position of the annotation to force a modified event to be triggered causing the table to update with the correct new value.
* **What is the new behaviour (if this is a feature change)?**
Now those events are being triggered, updating the table properly if the annotation has changed.
No breaking changes.
=> Trigger modified after getText and textChange callbacks

src/util/debugLib/index.js
Developer tools in Google chrome.Logging level support Verbose/Info/Warnings/Errors.
- [ X ] The commit message follows our guidelines
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)
bug fix
#1123 
N/A
N/A
i still wonder why remove lib debug. @dannyrb  this can also be …
=> fix #1123 latest version debug mode crash

src/util/freehand/pointInFreehand.js
Bug fix
#1160 
N/A
N/A
The pointInFreehand has a calculation error in the lineSegmentAtPoint and the isLineRightOfPoint;
> ```javascript
> /**
>  * Returns the y value of the line segment at the x value of the point.
>  * @private
>  * @method
>  * @name lineSegmentAtPoint
>  *
>  * @param {Object} point The point being queried.
>  * @param {Object} lp1 The first …
```
=> fix: pointInFreehand calculation error(cornerstonejs#1160)

src/stateManagement/imageIdSpecificStateManager.js
Expose [get|add|clear]ImageIdToolstate methods which allow managing imageId specific toolState without needing an element with the image loaded.
#1150
New feature
3 new methods on the `ImageIdSpecificToolStateManager` for managing toolState without needing an element.
```
getImageIdToolState,
addImageIdToolState,
clearImageIdToolState,
```
The signature for these matches that of the exising `add, get, clear` methods except that the first argument is an `imageId` instead of an element.
* **Does this PR …
=> feat(imageIdSpecificStateManager.js): Methods for managing toolState via imageId

docs/latest/modules/segmentation.md, src/store/modules/segmentationModule/addLabelmap2D.js, src/store/modules/segmentationModule/addLabelmap3D.js, src/store/modules/segmentationModule/arrayTypes.js, src/store/modules/segmentationModule/colorLUT.js, src/store/modules/segmentationModule/defaultConfiguration.js, src/store/modules/segmentationModule/getLabelmap2D.js, src/store/modules/segmentationModule/getLabelmapBuffers.js, src/store/modules/segmentationModule/getSegmentsOnPixeldata.js, src/store/modules/segmentationModule/index.js, src/store/modules/segmentationModule/setLabelmap3D.js, src/tools/segmentation/strategies/correction.js
Optional Float32Array storage for segmentations.
By setting the segmentation configuration property `arrayType` to `Float32Array` you can instead store the labelmap as a format more harmonious with `vtkjs`. `vtkjs` has to convert non-`Float32Array`s when generating textures to pass to the GPU, and this is very costly. If you are using vtkjs in your application its highly recommended to use `Float32Array`s for segmentations for decreased texture building times.
=> Optional Float32 segments

src/tools/OverlayTool.js
The initial position for DICOM overlays is now considered in OverlayTool.
The origin of DICOM overlays from the overlayPlaneModule was fixed to 0,0.
No
=> fix: OverlayTool now considers overlay initial position

src/tools/WwwcRegionTool.js, src/tools/WwwcTool.js
When applying window/level changes, we also set voiLUT to undefined to ensure any existing voiLUT is disabled.
The VOI LUT remains applied, so W/L changes do not take effect, which confuses the user.
The VOI LUT is disabled, and W/L proceeds as normal.
No
=> fix: Unset voiLUT when using WWWC or WWWCRegion tool

src/eventDispatchers/mouseEventHandlers/addNewMeasurement.js, src/eventDispatchers/touchEventHandlers/addNewMeasurement.js, src/manipulators/moveAllHandles.js, src/manipulators/moveHandle.js, src/manipulators/moveNewHandle.js, src/stateManagement/toolState.js, src/store/index.js, src/store/modules/manipulatorStateModule.js, src/tools/annotation/AngleTool.js, src/tools/annotation/ArrowAnnotateTool.js, src/tools/annotation/CobbAngleTool.js, src/util/uuidv4.js
Add in event cancelling for manipulators.
Paste this in the netlify demo console and then you can use ESC (at least on Chrome) to test `moveNewHandle`, `moveHandle` and `moveAllHandles`:
```
const cancelActiveManipulatorsForElement = cornerstoneTools.getModule(
'manipulatorState'
).setters.cancelActiveManipulatorsForElement;
const enabledElements = cornerstoneTools.store.state.enabledElements;
enabledElements.forEach(element => {
element.addEventListener('keydown', evt => {
if (evt.keyCode === 27) {
cancelActiveManipulatorsForElement(element);
}
});
});
```
Only cancelation of `moveNewHandle` will solve these issues.
Note that not all tools use manipulators, other tools would ideally be switched to use them (e.g. freehand tool, bidirectional tool).
=> Event cancelling for manipulators

src/manipulators/moveNewHandle.js, src/store/modules/manipulatorStateModule.js
#1195 broke click-move-click behavior for any tool using `moveNewHandle`, this fixes that.
Paste this in the console to test:
```
const enabledElements = cornerstoneTools.store.state.enabledElements;
const cancelActiveManipulatorsForElement = cornerstoneTools.getModule(
'manipulatorState'
).setters.cancelActiveManipulatorsForElement;
enabledElements.forEach(element => {
element.addEventListener('keydown', evt => {
if (evt.keyCode === 27) {
cancelActiveManipulatorsForElement(element);
}
});
});
```
=> Fix moveNewHandle

src/manipulators/moveNewHandle.js
cosmetic change to trigger publish messed up in previous PR. Nothing to see here.
=> fix: 🐛 Fixes moveNewHandle for click-move-click interaction

src/tools/annotation/AngleTool.js, src/tools/annotation/AngleTool.test.js, src/tools/annotation/CobbAngleTool.js
Only added in the Angle and CobbAngle tool: rowPixelSpacing and columnPixelSpacing default to 1
Bug fix
When there are no pixel spacing data of the image, the values of the angle measurements are not able to be calculated, since the getPixelSpacing function returns null for the rowPixelSpacing and columnPixelSpacing values.
Value 1 is used in the angle value calculation if the rowPixelSpacing and/or columnPixelSpacing values are null.
* **Does this PR introduce a breaking change?** (What changes might users …
=> Angle and CobbAngle tool: set default 1 for rowPixelSpacing and columnPixelSpacing

src/drawing/drawArrow.js, src/drawing/drawHandles.js, src/store/modules/globalConfigurationModule.js, src/tools/annotation/AngleTool.js, src/tools/annotation/ArrowAnnotateTool.js, src/tools/annotation/BidirectionalTool.js, src/tools/annotation/CircleRoiTool.js, src/tools/annotation/CobbAngleTool.js, src/tools/annotation/EllipticalRoiTool.js, src/tools/annotation/FreehandRoiTool.js, src/tools/annotation/LengthTool.js, src/tools/annotation/ProbeTool.js, src/tools/annotation/RectangleRoiTool.js, src/tools/annotation/bidirectionalTool/renderToolData.js
Dashed line rendering options for all tools.
Open the console and paste:
```js
const tools = cornerstoneTools.store.state.tools;
tools.forEach(tool => { const config = tool.configuration;  config.renderDashed = true; tool.configuration = config});
```
And all tools will be rendered in dashed mode. This can be done per tool, so you could have dashed in one viewport and solid in another.
The dash style is set in the `globalConfiguation` module, with a default lineDash of `[4,4]`.
=> feat: 🎸 Dashed rendering options for tools with lines/handles

src/tools/annotation/ArrowAnnotateTool.js
ArrowAnnotate incorrectly emitted events on cancel, this fixes add being called after a remove.
=> fix: 🐛 Fix ArrowAnnotate's event firing on complete/cancel

src/store/internals/removeEnabledElement.js, src/tools/MagnifyTool.js
- Fix cleanup of tools on disabling of magnify element.
- Prevent magnify orphans from being formed when an element is removed without tools being disabled.
This appears to fix the following issues:
RE: #1172 
RE: https://github.com/OHIF/Viewers/issues/1518
=> Magnify fix

src/util/convertToVector3.js, src/util/convertToVector3.test.js
In case the Vector3 `instanceof` doesn't match, but the object still has `{x,y,z}` values
No doc change needed
Kind of a bugfix/code hardening
If an object fails the `instanceof` check(which is currently happening for me, likely a webpack issue), it attempts to grab array values that don't exist, passing undefined to the constructor giving you a Vector3 of [0,0,0].
passing in a Vector3-like object will be properly converted to a Vector3
* **Does this PR introduce a breaking change?** (What changes might users …
=> Update convertToVector3 - handle similar objects

src/util/calculateSUV.js
`radiopharmaceuticalStartTime.fractionalSeconds` was not being checked in the `injectionStartTimeInSeconds` calculation. The fractional seconds are optional, and if not present, would cause a NaN and the SUV calculation would fail.
=> fix: 🐛 Fix SUV calculation if fractional seconds not present

src/synchronization/Synchronizer.js
Set fireEvent and onEvent functions from anonymous inner functions to object keys, to allow consumers to monkeypatch the functions of need be.
Minor feature
Anonymous inner functions in the Synchronizer class cannot be accessed or changed.
The changes allow for consumers to modify/extend Synchronizer behavior without having to create a whole new class
No
=> feat(Synchronizer): Change Scope of Event handlers

src/drawing/drawRect.js
`drawRect` was using a `moveTo` command between each `lineTo` which meant there was no polygon to fill. Removing the extra `moveTo` calls fixes `fillStyle`
Fixes #1299
Fix the `fillStyle` option on `drawRect`.
For details see #1299 
> Note that if you look closely, the corners are not connected in the before version
**Before:**
**After:**
**Before:**
**After:**
[![Edit hungry-mcclintock-ebt3s](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-mcclintock-ebt3s?fontsize=14&hidenavigation=1&theme=dark)
No
=> fix(drawing/drawRect.js): Fixes the fillStyle feature of drawRect.js

src/tools/RotateTool.js
Adds a rounding option to the RotateTool that rounds to integer numbers when configured.
Adds flipping direction option to change the CW/CCW direction that the mouse movement affects when using vertical/horizontal strategies
No integer rounding is applied, and the scale/angle values create tiny fractional angles, which do not display well. We could round the display of these numbers, but other logic in a vtkView uses whole integer angles.
Vertical strategy, down mousemovement is CW, and up is CCW.
Optional …
=> feat(RotateTool): Add rounded/integer angles option

src/tools/RotateTool.js
Feature/bugfix:
Removes horizontal/vertical strategy's usage of viewport scale to affect the amount of rotation,
causing inconsistent rotation amounts (and wild values on mobile devices). Applies user-configurable
scale and absolute distances in h/v strategies similar to default strategy.
Zoom level affects vertical/horizontal strategies.
Horizontal/Vertical strategies no longer scale the rotation amount by the image zoom level, but by a user-defined static value. 
Also employs the relative rotation from …
=> feat(RotateTool): Scale multiplier for rotate angle

src/requestPool/requestPoolManager.js
Cornerstone imageLoaders registered to cornerstone can take options which may specific to the loader themselves.
This PR adds an argument to the request pool manager to pass options down options to its managed `cornerstone.loadImage` and `cornerstone.loadAndCacheImage` calls.
These options are merged with the default options request pool manager provides.
=> Request pool manager options

src/synchronization/Synchronizer.js
Fixes the issue that Cornerstone was not being accessed correctly in Synchronizer.js for several functions
=> fix: Grab Cornerstone from external in Synchronizer

src/tools/annotation/EllipticalRoiTool.js
This is the same fix with #1320 for Elliptical ROI
=> fix(EllipticalRoiTool): Push stdDev to separate line for non-SUV modalities

src/eventListeners/mouseEventListeners.js, src/manipulators/moveNewHandle.js
This fixes #1337.  No breaking changes.  Just mitigating exceptions.
Currently, if you disable an element while a mouse button is held down, the two `onMouseMove` and `onMouseUp` listeners that are added _by_ the `mousedown` handler are not removed, causing an endless stream of exceptions.
To fix this, I've added a `Map` called `addedListeners` in the parent scope.  When `mousedown` is invoked, its `onMouseMove` and `onMouseUp` listeners get added to that Map.  If the problem scenario occurs, we now have a handle to all the generated listeners so we can remove them in the `disable` function.
I used the listener functions themselves as the keys in the Map because it is possible to have multiple `mousedown` and `mousemove` listeners when you have more than one mouse button pressed.
=> Remove any orphaned event listeners on disable (#1337)

src/tools/RotateTool.js, src/tools/RotateTool.test.js
- Bug fix: The RotateTool does not work on mobile device.
- The RotateTool does not work on mobile devices. viewport.initialRotation is undefined
- The RotateTool works fine on mobile devices.
I modified function defaultStrategy(evt) in RotateTool.js.
=> Fix rotate tool on mobile devices

package.json, src/stackTools/stackPrefetch.js
=> fix: StackPrefetch should use the imageLoadPoolManager

src/util/deepmerge.js
- When using the tool option svgCursor, one has to use the MouseCursor to instantiate the cursor object: 
```
import csTools from 'cornerstone-tools';
const MouseCursor = csTools.importInternal('tools/cursors/MouseCursor');
const cursor = new MouseCursor(
`
<g fill="ACTIVE_COLOR" stroke="ACTIVE_COLOR">
...
</g>
`,
{
viewBox: {
x: 100,
y: 100,
},
}
);
cornerstoneTools.addTool(cornerstoneTools.AngleTool, {
svgCursor: cursor,
});
```
The problem is that when passing the cursor object (instance of MouseCursor) as an option to the tool constructor, the deep merge that happens in the base tool just ignores the target's prototype: https://github.com/cornerstonejs/cornerstoneTools/blob/4e77512b79edd6d271fd249f841a80f71bee7ef0/src/tools/base/BaseTool.js#L35
This causes errors because the methods …
=> Update deep merge to resolve target prototype

src/eventDispatchers/mouseEventHandlers/addNewMeasurement.js
=> fix(moveNewHandler): Avoid ghost annotations on fast mouse events

src/eventListeners/internals/renderSegmentationFill.js, src/eventListeners/internals/renderSegmentationFill.test.js, src/eventListeners/internals/renderSegmentationOutline.js, src/eventListeners/internals/renderSegmentationOutline.test.js
This PR contains a bug fix.
The current behavior is that my overlay (rendered using the `Overlay Tool`) is getting resized and translated once the segmentation is rendered.
Note that the text is not even entirely on the screen, also there are two ellipsis that aren't even being shown, they appear on the screenshot below.
Now my overlay is not being resized nor translated and renders on the position where I expected it to be, also the segmentation kept working fine.
Now we can see that the text is well …
=> fix(SegRendering): preserve canvas transform matrix after seg render
